language: python

python:
  - "3.7"
  - "3.8"

sudo: required

before_install:
  - pip install pytest
  - "export DISPLAY=:99.0"

env:
  - DEPS="numpy matplotlib pandas"
    TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
    TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

install:
  - pip install codecov
  - pip install mock
  - pip install pytest-cov
  - pip install -r requirements.txt

script:
  - pytest test/test.py --cov=./

after_success:
  - codecov
